name: ChestRestock
main: com.dumptruckman.chestrestock.ChestRestock
version: maven-version-number
author: dumptruckman
softdepend: [Multiverse-Adventure]

commands:
  cr:
    description: Views/sets/changes the settings of the chest you are targetting.
    usage: /<command>